"""Added gender and pronouns to user model

Revision ID: 1de38aec4ceb
Revises: 1da900ba6484
Create Date: 2024-06-11 11:10:24.301146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de38aec4ceb'
down_revision = '1da900ba6484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('pronouns', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pronouns')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
