"""Add image URLs Columns to User Model

Revision ID: 1e208a223466
Revises: f0cae4ac696c
Create Date: 2025-07-28 10:17:18.662970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e208a223466'
down_revision = 'f0cae4ac696c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_1_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_2_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_3_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_4_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_5_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_5_url')
        batch_op.drop_column('image_4_url')
        batch_op.drop_column('image_3_url')
        batch_op.drop_column('image_2_url')
        batch_op.drop_column('image_1_url')

    # ### end Alembic commands ###
