"""Updated IPDemographics

Revision ID: 2098eea6b04b
Revises: 359de2a943fb
Create Date: 2025-08-18 14:19:22.399897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2098eea6b04b'
down_revision = '359de2a943fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('continent_code', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('continent', sa.String(length=20), nullable=True))
        batch_op.drop_column('data_source')
        batch_op.drop_column('region')
        batch_op.drop_column('city')
        batch_op.drop_column('isp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isp', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('data_source', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('continent')
        batch_op.drop_column('continent_code')

    # ### end Alembic commands ###
