"""Added OCEAN fields to User model

Revision ID: 25126412ea54
Revises: 
Create Date: 2024-06-10 09:30:17.514274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25126412ea54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('openness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('conscientiousness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extraversion', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agreeableness', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('neuroticism', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('neuroticism')
        batch_op.drop_column('agreeableness')
        batch_op.drop_column('extraversion')
        batch_op.drop_column('conscientiousness')
        batch_op.drop_column('openness')

    # ### end Alembic commands ###
