"""Add IP tracking tables

Revision ID: 359de2a943fb
Revises: 1e208a223466
Create Date: 2025-08-18 10:48:46.076312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359de2a943fb'
down_revision = '1e208a223466'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('isp', sa.String(length=200), nullable=True),
    sa.Column('time_zone', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('user_ip_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_ip', sa.String(length=45), nullable=True))
        batch_op.add_column(sa.Column('current_country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ip_last_updated', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('ip_last_updated')
        batch_op.drop_column('current_country')
        batch_op.drop_column('current_ip')

    op.drop_table('user_ip_log')
    op.drop_table('ip_demographics')
    # ### end Alembic commands ###
