"""Add IP tracking tables again

Revision ID: 47dfb63b213b
Revises: 2098eea6b04b
Create Date: 2025-08-18 14:46:39.856292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dfb63b213b'
down_revision = '2098eea6b04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_demographics', schema=None) as batch_op:
        batch_op.drop_column('time_zone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_demographics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_zone', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
