"""Added message field

Revision ID: 655f13c8e714
Revises: 085b1c96619b
Create Date: 2024-06-17 15:32:21.999934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655f13c8e714'
down_revision = '085b1c96619b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=140), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=80), nullable=True))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.VARCHAR(length=140), nullable=False))
        batch_op.drop_column('username')
        batch_op.drop_column('message')

    # ### end Alembic commands ###
