"""Improved Image storage

Revision ID: 9c162bddd2f9
Revises: 174c5b79df66
Create Date: 2025-08-21 11:52:25.674683

"""
from alembic import op
import sqlalchemy as sa


# import custom types
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
try:
    from app.custom_types import EncryptedString, decrypt_encrypted_field
    # Make them available in the global namespace for the migration
    globals()['EncryptedString'] = EncryptedString
    globals()['decrypt_encrypted_field'] = decrypt_encrypted_field
except ImportError as e:
    # Fallback for migrations that don't need custom types
    print(f"Warning: Could not import custom types: {e}")
    class EncryptedString:
        pass
    globals()['EncryptedString'] = EncryptedString

# revision identifiers, used by Alembic.
revision = '9c162bddd2f9'
down_revision = '174c5b79df66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_1_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_2_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_3_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_4_data', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('image_5_data', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('image_1_url')
        batch_op.drop_column('image_5_url')
        batch_op.drop_column('image_3_url')
        batch_op.drop_column('image_2_url')
        batch_op.drop_column('image_4_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_4_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_2_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_3_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_5_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('image_1_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('image_5_data')
        batch_op.drop_column('image_4_data')
        batch_op.drop_column('image_3_data')
        batch_op.drop_column('image_2_data')
        batch_op.drop_column('image_1_data')

    # ### end Alembic commands ###
