"""Add investment_profile to User model

Revision ID: a94bed469d6c
Revises: 7f745a7d22ad
Create Date: 2024-06-25 15:20:59.213962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94bed469d6c'
down_revision = '7f745a7d22ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_profile', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('investment_profile')

    # ### end Alembic commands ###
