"""switch sensitive fields to EncryptedString

Revision ID: c9e68b7c10bd
Revises: 47dfb63b213b
Create Date: 2025-08-19 13:44:30.807186

"""
from alembic import op
import sqlalchemy as sa


# import custom types
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
try:
    from app.custom_types import EncryptedString
except ImportError:
    # Fallback for migrations that don't need custom types
    pass

# revision identifiers, used by Alembic.
revision = 'c9e68b7c10bd'
down_revision = '47dfb63b213b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ip_demographics', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=EncryptedString(),
               existing_nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=100),
               type_=EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('country_code',
               existing_type=sa.VARCHAR(length=2),
               type_=EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('continent_code',
               existing_type=sa.VARCHAR(length=2),
               type_=EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('continent',
               existing_type=sa.VARCHAR(length=20),
               type_=EncryptedString(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_ip',
               existing_type=sa.VARCHAR(length=45),
               type_=EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('current_country',
               existing_type=sa.VARCHAR(length=100),
               type_=EncryptedString(),
               existing_nullable=True)

    with op.batch_alter_table('user_ip_log', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.VARCHAR(length=45),
               type_=EncryptedString(),
               existing_nullable=False)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=500),
               type_=EncryptedString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ip_log', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_country',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('current_ip',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)

    with op.batch_alter_table('ip_demographics', schema=None) as batch_op:
        batch_op.alter_column('continent',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('continent_code',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('country_code',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
        batch_op.alter_column('country',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=EncryptedString(),
               type_=sa.VARCHAR(length=45),
               existing_nullable=False)

    # ### end Alembic commands ###
